/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ChecksBus.Funcionario;
import ChecksBus.Terminal;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ChecksBus.org
 */
public class Administrar_Cuenta extends javax.swing.JFrame {
    
    
    private boolean validarRegreso;

    /**
     * Creates new form Administrar_Cuenta
     */
    Terminal terminal = new Terminal();
    Funcionario funcionario = new Funcionario();

    /**
     *
     */
    public Administrar_Cuenta() {
        initComponents();
        funcionario.archivo.cargar_Funcionario_txt(terminal.empresa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        TxtNombre1 = new javax.swing.JTextField();
        TxtContraseña1 = new javax.swing.JPasswordField();
        TxtNombre2 = new javax.swing.JTextField();
        TxtContraseña2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JbOk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TxtContraseña3 = new javax.swing.JPasswordField();
        jButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombre2KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Ingrese usuario:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese nuevo usuario:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese contraseña:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Ingrese nueva contraseña:");

        JbOk.setText("Ok");
        JbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbOkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Ingrese nuevamente nueva contraseña:");

        TxtContraseña3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtContraseña3KeyTyped(evt);
            }
        });

        jButton.setText("Atras");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JbOk)
                .addGap(243, 243, 243))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtContraseña2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContraseña1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContraseña3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtContraseña3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbOk)
                    .addComponent(jButton))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbOkActionPerformed
        int pos = terminal.validarUsuarios(TxtNombre1.getText(),new String(TxtContraseña1.getPassword()).trim().replace(" ", "_"), 1);
        Login login = new Login();
        if ( pos != -1){
            funcionario = terminal.empresa.obtenerRegistroFuncionario(pos);
            JOptionPane.showMessageDialog(null, "Volver a logearse");
            login.setVisible(true);
            dispose();
        }else{
            pos = terminal.validarUsuarios(TxtNombre1.getText(),new String(TxtContraseña1.getPassword()).trim().replace(" ", "_"), 0);
            if (pos != -1) {
                funcionario = terminal.empresa.obtenerRegistroFuncionario(pos);
                JOptionPane.showMessageDialog(null, "Volver a logearse");
                login.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
            }
        }
    }//GEN-LAST:event_JbOkActionPerformed

    private void TxtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombre2KeyTyped
        char teclaPresionadas = evt.getKeyChar();
        if (teclaPresionadas == KeyEvent.VK_ENTER && TxtNombre2.getText() != null) {
            funcionario.setNombreusuario(TxtNombre2.getText());
            funcionario.getArchivo().modificarRegistroFuncionario(funcionario.getIdentificadorAleatorio(), funcionario, terminal.empresa);
            JbOk.doClick();
        }
    }//GEN-LAST:event_TxtNombre2KeyTyped

    private void TxtContraseña3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtContraseña3KeyTyped
        char teclaPresionadas = evt.getKeyChar();
        if (teclaPresionadas == KeyEvent.VK_ENTER && new String(TxtContraseña2.getPassword()) != null) {
            if (new String(TxtContraseña2.getPassword()).equals(new String(TxtContraseña3.getPassword()))) {
                funcionario.setContrasena(new String(TxtContraseña3.getPassword()));
                funcionario.getArchivo().modificarRegistroFuncionario(funcionario.getIdentificadorAleatorio(), funcionario, terminal.empresa);
                JbOk.doClick();
            }else{
                JOptionPane.showMessageDialog(null, "contraseña no coinciden");
            }
        }
    }//GEN-LAST:event_TxtContraseña3KeyTyped

    
    
    /** 
     * Metodo que se utiliza para validar el tipo de usuario de que esta ingresando a administrar su cuenta para luego volver a su menu correspondiente. Si es verdadero se asume que es es usuario administrador,
     * si es falso se asume que es un usuario funcionario normal
     * @param opcion Tipo boleano 
     */
    public void validarAtras(boolean opcion){
        this.validarRegreso=opcion;
    }
    
    
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        if (validarRegreso) {
            MenuFuncionarioAdmin menu = new MenuFuncionarioAdmin();
            menu.setVisible(true);
        }else{        
            MenuFuncionario m = new MenuFuncionario();
            m.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_jButtonActionPerformed

    
    
    /**        

     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrar_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrar_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbOk;
    private javax.swing.JPasswordField TxtContraseña1;
    private javax.swing.JPasswordField TxtContraseña2;
    private javax.swing.JPasswordField TxtContraseña3;
    private javax.swing.JTextField TxtNombre1;
    private javax.swing.JTextField TxtNombre2;
    protected javax.swing.JButton jButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
