/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.table.DefaultTableModel;
import ChecksBus.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ChecksBus.org
 */
public class MostrarAgregarFuncionarios extends javax.swing.JFrame {

    
    //Atrivutos
    private Terminal terminal = new Terminal();

    /**
     *
     */
    public Funcionario funcionario = new Funcionario();
    /**
     * Creates new form EditarFuncionarios
     */
    public MostrarAgregarFuncionarios() {
        initComponents();
        try{
        funcionario.archivo.cargar_Funcionario_txt(terminal.empresa);
         listarRegistro();
        TxtNombreEmpresa.setText("TurBus");
        TxtNombreEmpresa.setEditable(false);//No se puede editar el campo de texto de la Empresa
        }catch(Exception e){
            mensaje("No carga txt");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modficar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jFmodificar = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtApellido = new javax.swing.JTextField();
        TxtUsuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        TxtNombreEmpresa = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        TxtContraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        TxtContraseña2 = new javax.swing.JPasswordField();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        Modficar.setText("jMenuItem1");
        jPopupMenu1.add(Modficar);

        jMenuItem2.setText("jMenuItem2");
        jPopupMenu1.add(jMenuItem2);

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jFmodificarLayout = new javax.swing.GroupLayout(jFmodificar.getContentPane());
        jFmodificar.getContentPane().setLayout(jFmodificarLayout);
        jFmodificarLayout.setHorizontalGroup(
            jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFmodificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFmodificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFmodificarLayout.setVerticalGroup(
            jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFmodificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jFmodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFmodificarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        txtNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNombre.setText("Nombre:");

        txtApellido.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtApellido.setText("Apellido:");

        txtEmpresa.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtEmpresa.setText("Empresa:");

        txtContraseña.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtContraseña.setText("Contraseña:");

        txtUsuario.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtUsuario.setText("Usuario:");

        btnGuardar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        atras.setText("Volver");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        TxtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEmpresaActionPerformed(evt);
            }
        });

        txtNombre1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtNombre1.setText("Identificador:");

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña nuevamente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNombre)
                                    .addComponent(TxtUsuario)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(txtEmpresa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(btnGuardar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(txtNombre1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtId)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton2)
                                .addGap(135, 135, 135)
                                .addComponent(btnEliminar)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtContraseña)
                                        .addComponent(txtApellido)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(TxtContraseña)
                                    .addComponent(TxtContraseña2))
                                .addGap(33, 33, 33)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre1)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido)
                            .addComponent(TxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContraseña)
                            .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TxtContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atras)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
      ingresarRegistroFuncionario(leerId(), leerNombre(), leerApellido(), leerNombreEmpresa(), leerUsuario(),
            leerContraseña(), 1 , terminal.empresa);
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    
    
    private void ingresarRegistroFuncionario(int id, String nombre, String apellido, String nombreEmpresa, String usuario,
            String contraseña, int rol , Empresa empresa){
       
            if(id != -1 && id<0)mensaje("Ingresar codigo entero");
            else if(nombre == null)mensaje("Ingresar Nombre");
            else if(apellido == null) mensaje("Ingresar Apellido");
            else if(nombreEmpresa == null)mensaje("Ingresar Nombre de Empresa");
            else if(usuario== null)mensaje("Ingresar Usuario");
            else if(contraseña== null)mensaje("Ingresar Contraseña");
            else{
                empresa.admin = new Funcionario(id, nombre, apellido, usuario, contraseña, rol);
                if(empresa.buscaCodigoFuncionario(empresa.getAdmin().getIdentificadorAleatorio())!= -1)mensaje("Este codigo ya existe");
                else empresa.agregarRegistroFuncionario(empresa.admin);
                funcionario.getArchivo().grabar_Funcionario_txt(empresa.admin,empresa);
                listarRegistro();
                LimpiarCampos();
            }
            
    }
    
    
    /**
     * Metodo que limpia todos los campos de texto jTextField
     */
    private void LimpiarCampos(){
        this.jTxtId.setText(null);
        this.TxtNombre.setText(null);
        this.TxtApellido.setText(null);
        this.TxtNombreEmpresa.setText(null);
        this.TxtUsuario.setText(null);
        this.TxtContraseña.setText(null);
    }
     private int leerId(){
        try{
            int id = Integer.parseInt(jTxtId.getText().trim());
            return id;
        }catch(NumberFormatException ex){
            return -1;
        }
     }
      private String leerNombre(){
        try{
            String nombre = this.TxtNombre.getText().trim().replace(" ", "_");
            return nombre;
        }catch(Exception ex){
            return null;
        }
      }
       private String leerApellido(){
        try{
            String apellido = TxtApellido.getText().trim().replace(" ", "_");
            return apellido;
        }catch(Exception ex){
            return null;
        }
       }
        private String leerNombreEmpresa(){
        try{
            String empresa = this.TxtNombreEmpresa.getText().trim().replace(" ", "_");
            return empresa;
        }catch(Exception ex){
            return null;
        }
        }
        private String leerUsuario(){
        try{
            String usuario = TxtUsuario.getText().trim().replace(" ", "_");
            return usuario;
        }catch(Exception ex){
            return null;
        }
        }
         private String leerContraseña(){
        try{
            String contraseña = new String(TxtContraseña.getPassword()).trim().replace(" ", "_");
            return contraseña;
        }catch(Exception ex){
            return null;
        }
         }
         private String leerNuevamenteContraseña(){
             try{
            String contraseña = new String(TxtContraseña2.getPassword()).trim().replace(" ", "_");
            return contraseña;
        }catch(Exception ex){
            return null;
        }
         }

    /**
     *
     * @param texto
     */
    public final void mensaje(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    if(leerId() != 1){     
    funcionario.archivo.eliminarRegistroFuncionario(leerId(), terminal.empresa);
    listarRegistro();
    }else { mensaje("No se puede eliminar");}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TxtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEmpresaActionPerformed
        
    }//GEN-LAST:event_TxtNombreEmpresaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ModificarFuncionario fun = new ModificarFuncionario();
       fun.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        MenuFuncionarioAdmin menu = new MenuFuncionarioAdmin();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     *
     */
    public final void listarRegistro(){
        DefaultTableModel modelo = new DefaultTableModel(){//objeto que modifica 
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        modelo.addColumn("Identificador");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Empresa");
        modelo.addColumn("Nombre de Usuario");       
        
 
        
        Object fila[] = new Object[modelo.getColumnCount()];
        
        for (int i = 0; i < terminal.empresa.getTrabajadores().size(); i++) {
            funcionario = terminal.empresa.getTrabajadores().get(i);
            if(funcionario.getRol() == 1){
            fila[0]= funcionario.getIdentificadorAleatorio();
            fila[1]= funcionario.getNombre();
            fila[2]= funcionario.getApellido();
            fila[3]= "Turbus";
            fila[4]= funcionario.getNombreusuario();
            modelo.addRow(fila);
            }
        }
        
        tabla.setModel(modelo);
        tabla.setRowHeight(60);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarAgregarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarAgregarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarAgregarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarAgregarFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarAgregarFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Modficar;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JPasswordField TxtContraseña2;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNombreEmpresa;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JButton atras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtContraseña;
    private javax.swing.JLabel txtEmpresa;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
